version: '3'
services:

    app:
        build:
            dockerfile: ./app-java.dockerfile
            context: .
        image: robertomassoni/app-java
        ports:
            - "80:8080"
        environment:
            SPRING_PROFILES_ACTIVE: prod
            APP_DATABASE_URL: jdbc:mysql://142.93.193.132:3306/xyinc_db
            APP_DATABASE_USERNAME: root
            APP_DATABASE_PASSWORD: 1234            
        networks: 
            - production-network   
        depends_on:
            - "db"    

    db:
        build:
            dockerfile: ./mysql.dockerfile
            context: .
        image: robertomassoni/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        networks: 
            - production-network   

networks: 
    production-network:
        driver: bridge
