-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 21:35:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xyinc_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xyinc_db` ;

-- -----------------------------------------------------
-- Schema xyinc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xyinc_db` DEFAULT CHARACTER SET utf8 ;
USE `xyinc_db` ;

-- -----------------------------------------------------
-- Table `xyinc_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyinc_db`.`category` ;

CREATE TABLE IF NOT EXISTS `xyinc_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyinc_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyinc_db`.`product` ;

CREATE TABLE IF NOT EXISTS `xyinc_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `category_id` INT NOT NULL,
  `price` DECIMAL(14,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `xyinc_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyinc_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyinc_db`.`user` ;

CREATE TABLE IF NOT EXISTS `xyinc_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyinc_db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyinc_db`.`role` ;

CREATE TABLE IF NOT EXISTS `xyinc_db`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyinc_db`.`role_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyinc_db`.`role_has_user` ;

CREATE TABLE IF NOT EXISTS `xyinc_db`.`role_has_user` (
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `fk_role_has_user1_user1_idx` (`user_id` ASC),
  INDEX `fk_role_has_user1_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_has_user1_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `xyinc_db`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_user1_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `xyinc_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `xyinc_db`.`category` (`name`) VALUES ('Eletronics');
INSERT INTO `xyinc_db`.`product` (`name`, `category_id`) VALUES ('Tv', '1');
INSERT INTO `xyinc_db`.`product` (`name`, `category_id`) VALUES ('Mouse', '1');
INSERT INTO `xyinc_db`.`product` (`name`, `category_id`) VALUES ('Notebook', '1');
INSERT INTO `xyinc_db`.`product` (`name`, `category_id`) VALUES ('Video Game', '1');
INSERT INTO `xyinc_db`.`role` (`name`) VALUES ('Admin');
INSERT INTO `xyinc_db`.`user` (`name`, `email`, `password`) VALUES ('Roberto', 'robertopmassoni@gmail.com', '$2a$10$XLeTQIQ2tbv7hwni9BnqXuOshhQpVv55YkJropXuTsO1dHRxnP5H6');